name: iOS Build & TestFlight

on:
  push:
    branches:
      - main

jobs:
  trigger-eas-workflow:
    name: Trigger EAS Production Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.WORDS_TYPES_TOKEN }}

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Trigger EAS Workflow
        run: eas workflow:run .eas/workflows/create-production-builds.yml --non-interactive
